<a href="https://colab.research.google.com/github/Hassan-jr/Tensorflow-Deep-Learning/blob/main/00_Fundamentals_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [1]:
import tensorflow as tf

In [7]:
v = tf.constant(7)
v


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
s = tf.constant([1,2,3,4])
s

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [10]:
s.numpy()

array([1, 2, 3, 4], dtype=int32)

In [11]:
s.dtype

tf.int32

In [12]:
s.shape

TensorShape([4])

In [15]:
tf.size(s)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [16]:
m = tf.constant([[1,2,3],
                 [4,5,6],
                [7,8,9]])
m

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [17]:
m.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [18]:
m.shape

TensorShape([3, 3])

In [20]:
tf.size(m)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [23]:
tf.rank(m)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [24]:
tf.rank(v)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [25]:
tf.rank(s)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

# Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [71]:
tf.random.set_seed(42)
tensor_1 = tf.random.uniform(shape=(5,300),maxval=1)
tensor_2 = tf.random.uniform(shape=(5,300),maxval=1)
tensor_1[:10], tensor_2[:10]

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

In [48]:
tensor_1.shape, tensor_2.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

In [51]:
tensor_2_reshaped = tf.reshape(tensor_2, shape=(300,5))
tensor_2_reshaped[:10]
tensor_2_reshaped.shape

TensorShape([300, 5])

In [54]:
t1t2 = tf.matmul(tensor_1, tensor_2_reshaped)
t1t2

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.2758  , 79.17824 , 77.82306 , 79.38919 , 79.37956 ],
       [72.706345, 73.675156, 73.71575 , 74.184204, 73.72947 ],
       [75.74081 , 76.490845, 74.435486, 78.802124, 77.70212 ],
       [68.98616 , 75.53636 , 74.58009 , 76.192314, 75.25122 ],
       [75.56367 , 81.7986  , 78.68144 , 80.15668 , 80.48313 ]],
      dtype=float32)>

In [58]:
t1t2_2 = tf.tensordot(tensor_1,tensor_2_reshaped, axes=1)
t1t2_2

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.2758  , 79.17824 , 77.82306 , 79.38919 , 79.37956 ],
       [72.706345, 73.675156, 73.71575 , 74.184204, 73.72947 ],
       [75.74081 , 76.490845, 74.435486, 78.802124, 77.70212 ],
       [68.98616 , 75.53636 , 74.58009 , 76.192314, 75.25122 ],
       [75.56367 , 81.7986  , 78.68144 , 80.15668 , 80.48313 ]],
      dtype=float32)>

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [73]:
tf.random.set_seed(42)
A = tf.random.uniform(shape=(224,224,3), maxval=1)
A[0]

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[6.64562106e-01, 4.41006780e-01, 3.52882504e-01],
       [4.64482546e-01, 3.36604118e-02, 6.84672356e-01],
       [7.40117431e-01, 8.72444510e-01, 2.26326346e-01],
       [2.23196864e-01, 3.10388088e-01, 7.22335815e-01],
       [1.33187175e-01, 5.48063874e-01, 5.74608803e-01],
       [8.99683475e-01, 9.46366787e-03, 5.21230698e-01],
       [6.34544492e-01, 1.99328303e-01, 7.29422450e-01],
       [5.45834541e-01, 1.07565522e-01, 6.76706076e-01],
       [6.60276294e-01, 3.36950421e-01, 6.01417661e-01],
       [2.10625768e-01, 8.52737188e-01, 4.40621734e-01],
       [9.48527575e-01, 2.37525940e-01, 8.11792970e-01],
       [5.26339412e-01, 4.94307995e-01, 2.16128469e-01],
       [8.45719695e-01, 8.71884108e-01, 3.08386207e-01],
       [6.86803818e-01, 2.37640381e-01, 7.81722784e-01],
       [9.67138410e-01, 6.87016249e-02, 7.98739433e-01],
       [6.60287142e-01, 5.87151289e-01, 1.64616942e-01],
       [7.38102317e-01, 3.20540428e-01

In [66]:
A_min = tf.reduce_min(A) 
A_max = tf.reduce_max(A)
A_min, A_max

(<tf.Tensor: shape=(), dtype=float32, numpy=3.5762787e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.999998>)

# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [78]:
B = tf.random.uniform(shape = (1,224,224,3))
C = tf.squeeze(B)
B.shape,C.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [79]:
D = tf.constant([0,1,2,3,4,5,6,7,8,9])
D_max = tf.argmax(D)
D.shape, D_max

(TensorShape([10]), <tf.Tensor: shape=(), dtype=int64, numpy=9>)

# One-hot encode the tensor you created in 9.

In [80]:
E = tf.one_hot(D,depth=10)
E

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [81]:
tf.__version__

'2.11.0'